# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # base box
  config.vm.box = "ubuntu/trusty64"

  # install node
  config.vm.provision "shell", path: "install-node.sh"
end
